;; -*- geiser-scheme-implementation: chez-*-
(optimize-level 2)
(load "utilities.scm")
(load "note.scm")
(load "rhythm.scm")
(load "note-dsl.scm")
(import utilities)
(import note)
(import rhythm)
(import note-dsl)
